version: '3.4'

services:
  init-genesis-and-validators:
    image: ${IMAGE_BESU}
    network_mode: host
    volumes:
      - ${CONFIG_INIT_ROOT}/:/var/lib/besu/
    command: >-
        operator generate-blockchain-config
          --config-file="/var/lib/besu/genesis-config.json"
          --to="/var/lib/besu/generate-blockchain/"
          --private-key-file-name=key
  init-bootnode:
    image: ${IMAGE_BESU}
    network_mode: host
    environment:
      - BESU_DATA_PATH=/var/lib/besu/keys-bootnodes/${NODE_NAME}
    volumes:
      - ${CONFIG_INIT_ROOT}/:/var/lib/besu/
    command: public-key export --to="/var/lib/besu/keys-bootnodes/${NODE_NAME}/key.pub"
