#!/usr/bin/env bash

__EXEC__="$(realpath -s ${BASH_SOURCE[0]})"
__DIRE__="${__EXEC__%/*}"
__FILE__="$(readlink -f ${BASH_SOURCE[0]})"
__DIR__="${__FILE__%/*}"

set -e

source "${__DIR__}/common/besu.sh"
source "${__DIR__}/common/json.sh"

shopt -s nullglob

for envfile in .env.defaults* .env.local*; do
	source $envfile
done

shopt -u nullglob

CONFIG_ROOT=${CONFIG_ROOT:-"${PWD}/.env.configs"}
VOLUMES_ROOT=${VOLUMES_ROOT:-"${PWD}/volumes"}

# configuration

[[ -n "${BOOT_NODES+x}" ]] || BOOT_NODES=${BOOT_NODES:-$(seq -f "${BOOT_PREFIX:-boot}%.0f" ${BOOT_COUNT:-0})}
[[ -n "${VALIDATOR_NODES+x}" ]] || VALIDATOR_NODES=${VALIDATOR_NODES:-$(seq -f "${VALIDATOR_PREFIX:-validator}%.0f" ${VALIDATOR_COUNT:-0})}
[[ -n "${WRITER_NODES+x}" ]] || WRITER_NODES=${WRITER_NODES:-$(seq -f "${WRITER_PREFIX:-writer}%.0f" ${WRITER_COUNT:-0})}

ALL_NODES="${BOOT_NODES} ${VALIDATOR_NODES} ${WRITER_NODES}"

STATIC_NODES_PATH="${CONFIG_ROOT}/static-nodes.json"
GENESIS_PATH="${CONFIG_ROOT}/genesis.json"

mkdir -p "${CONFIG_ROOT}" "${VOLUMES_ROOT}"

# create nodes
for NODE_NAME in ${ALL_NODES}; do
	NODE_CONFIG_PATH="${CONFIG_ROOT}/nodes/${NODE_NAME}"
	NODE_DATA_PATH="${VOLUMES_ROOT}/${NODE_NAME}"

	mkdir -p "${NODE_CONFIG_PATH}" "${NODE_DATA_PATH}"
	chown 1000.1000 "${NODE_CONFIG_PATH}" "${NODE_DATA_PATH}"

	if [[ -f "${NODE_CONFIG_PATH}/key" ]]; then
		continue
	fi

	besu_generate_keypair "${NODE_CONFIG_PATH}"
done

# create/expand static-nodes.json
VALIDATOR_ENODES=$(for NODE_NAME in ${VALIDATOR_NODES}; do
	NODE_CONFIG_PATH="${CONFIG_ROOT}/nodes/${NODE_NAME}"
	besu_get_enode ${NODE_CONFIG_PATH}
done | json_array)

if [[ -f "${STATIC_NODES_PATH}" ]]; then
	cat "${STATIC_NODES_PATH}"
else
	printf '[]'
fi | jq -s "(.[0] + ${VALIDATOR_ENODES} | unique)" >"${STATIC_NODES_PATH}"

# create genesis.json
if ! besu_genesis_ready "${GENESIS_PATH}"; then
	GENESIS_EXTRADATA=$(for NODE_NAME in ${VALIDATOR_NODES}; do
		NODE_CONFIG_PATH="${CONFIG_ROOT}/nodes/${NODE_NAME}"
		besu_get_address "${NODE_CONFIG_PATH}"
	done | json_array | besu_encode_rlp)

	BOOT_ENODES=$(for NODE_NAME in ${BOOT_NODES}; do
		NODE_CONFIG_PATH="${CONFIG_ROOT}/nodes/${NODE_NAME}"
		besu_get_enode "${NODE_CONFIG_PATH}"
	done | json_array)

	TIMESTAMP_HEX=$(printf '0x%X' $(date +%s))

	if [[ -f "${GENESIS_PATH}" ]]; then
		cat "${GENESIS_PATH}"
	else
		cat <<-EOF
			{
			  "config": {
			    "chainId": 648629,
			    "constantinopleFixBlock": 0,
			    "berlinBlock": 0,
			    "contractSizeLimit": 2147483647,
			    "ibft2": { "blockperiodseconds": 2, "epochlength": 30000, "requesttimeoutseconds": 4 },
			    "discovery": { "bootnodes": [] }
			  },
			  "nonce": "0x0",
			  "gasLimit": "0x2FEFD800",
			  "difficulty": "0x1",
			  "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
			  "coinbase": "0x0000000000000000000000000000000000000000"
			}
		EOF
	fi |
		jq ".extraData = \"${GENESIS_EXTRADATA}\"" |
		jq ".timestamp = \"${TIMESTAMP_HEX}\"" |
		jq ".config.discovery.bootnodes = (.config.discovery.bootnodes + ${BOOT_ENODES} | unique)" >"${GENESIS_PATH}"
fi

# render templates
"${__DIR__}/template-render"
