#!/usr/bin/env bash

target="${1}"
method="${2}"
params="${@:3}"
params="${params:-[]}"

source .dtoolx/scripts/common.sh

curl -skX POST \
	--data "$(printf '{ "jsonrpc": "2.0", "method": "%s", "params": %s, "id": 1 }' "${method}" "${params}")" \
	http://localhost:${APP_WEB_PORT}/nodes/${target}
