#!/usr/bin/env bash

__EXEC__="$(realpath -s ${BASH_SOURCE[0]})"
__DIRE__="${__EXEC__%/*}"
__FILE__="$(readlink -f ${BASH_SOURCE[0]})"
__DIR__="${__FILE__%/*}"

set -e

source "${__DIR__}/common/template.sh"

shopt -s nullglob

for envfile in .env.defaults* .env.local*; do
	source $envfile
done

shopt -u nullglob

CONFIG_ROOT=${CONFIG_ROOT:-"${PWD}/.env.configs"}
VOLUMES_ROOT=${VOLUMES_ROOT:-"${PWD}/volumes"}

TEMPLATE_DATA=$("${__DIR__}/node-list")

find -L "${PWD}" "${CONFIG_ROOT}" ! -path '*~/*' ! -path '*/.git/' -name '*.hbs' -printf '%h\n' | sort -u |
	while read TEMPLATE_DIR; do
		cat <<-EOF | template_render "${TEMPLATE_DIR}"
			${TEMPLATE_DATA}
		EOF
	done
